before:
builds:
  - main: ./urlsplit.go
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
archive:
  replacements:
    darwin: osx
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brew:
  github:
    owner: relvacode
    name: homebrew-urlsplit
