language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux && $LATEST = true"
env:
  global:
    secure: az8obnpIeSEQlRQKWYgN6m8CNMY34vKYc8Lpar/vJM91epJxdqRplu8+/4tHzY3gDG2HnZsagYTCLbxTNJXHOTZrRBrDmJsXPyqwoqaW65nksyOgZnkS1hPsc+2yn8CRYkTEh2RZRY4G41zbkR8DJzHxsiLjY/W0D3SSCoDXCh3wjGh0GqeT5YH/FCUut7A3Tt6tlu/VhGv0tnOZPCA02IxH0dVR8TwLwjmBXfLSM+LYvrStDunZ+wA1KbhnFg9Li7eWv+3OupHZjpN/mnMnCkAi/qaRodM3AKkw6yWv6R6ZTfBbVU9Unrinu5p5l2EUk3+ZF6xbrVNb/AqDDyCOj6MZmFANHDYoEuD1sEyMhsXv8fwPfDysb9hDDtkmJ4ZqquWOnVZ84kLB6ZHHJttP91+w6e9GHfH+/6y2oy4FPHShZ/1U1BPzgKACcKrFJKF0TiyL7PL12wmSVEwjrr9B5ioqJNnd+wytwB9fwO5sDnVqtYSN4FLxvjrxFhqhiPPEgjk0h1767awN6FanpmV5mhO8K+rSTg/0HxyL3fjVOuk2yVycbBfuL30vdNfhGzeg0SBIWIjeTZyqyZMycPCMuigRAa77OlFK65qXrpcN4JdPVsLYBvI1oQl2lwNo6HOjGZZnUoe6Ry+h6k1Ex+OpuEdUx3bD3OpVlcORUV96Kk8=
